#!/bin/bash

# Description: List all dotfiles

for file in $HOME/dotfiles/*; do
    # [[ "$file" == .* ]] && echo "Hidden file: $file" && continue
    [[ -f "$file" ]] || continue
    echo "$file"
done
